language: node_js
node_js:
    - stable
deploy:
    provider: npm
    email: info@collectorbank.se
    api_key:
        secure: ZfNKGl4eG0nPrbu6Zh09XVKqR+FNPPoFfW/6j1wP5d0L5TXOStQ2SlppibWFEd8s5C25Ni7mJgJcOakJrFkW5TTu3D7EM++5zJk322pIil1QO+d2CQ5mZ8wSU/OEepz9OaS1/OthzJaq9O6srJhx/Sq+BuwLe28HvvHTtP1jM513rJ9jXAavumB+gyg/WKsgqqKyMGmMvKMu1eOvRFcU/PwRIgzF9KPLeYQfyisNf0Co8yABVF22xG6bb9eNXxEgASvjXf+Aa0zRU7GyR5RagHZFIseg1aCwKK6iQ3AgeMYEGONUO6FT2v7vNtK21g/a5v1RW3DnaaggESRcRxEh+tOsNpYLmjVHg+ewDGNT+wPsGMcvhU0HcF2UA5QihYKhdXaAl1EXtLLjqpKwiHQtiiiKLRItdoTM3ovvtrPrSvrzJQqsBLsrVL+r3DvnUBIKd2pPUAuXSvP3YHuoWxFanAhRBW/OthpdJ8oZMUzWUv27+N/W+QUfBrvSFdGXYtM6LzSlAc8yPyUXtbDbcE7+J+0KfUeHpAJ2mv6ZbsYOVquKF1RrqRAAaUaQpxs9B9v2UFbDZEvmuSYNu0g+Q0/K3DNmMO9DlNgy0B7ul/YSHGYQsHT6QadW0dhzq3haDuSyAG675l/SCoiWamOy7gUyLNOlQqr7+rkRS+8gOzU68Mo=
    on:
        repo: collector-bank/collector-compliance-form
        branch: master
    skip_cleanup: true
